### ISSUE TITLE
Offline version?

### ISSUE THREAD

**Issue by Epictyphlosion** [SthephanShinkufag/bytebeat-composer#76]
Is it possible for there to be an offline version of the site? I've downloaded the repo and have tried to run it, but none of the scripts work.

**Comment by SthephanShinkufag** [comment]
No.

**Comment by SArpnt** [comment]
you need to run a [local web server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server)

**Comment by codermannnnnnn** [comment]
how do i run a local web server

**Comment by Epictyphlosion** [comment]
@SArpnt After a long time, I've finally gotten around to installing XAMPP. Running it through there still gives me the same issues when trying to run it from the HTML file: The audio won't start and all of the library entries are empty. I also run into a `globalThis.bytebeat is undefined` error, attributed to character 350715 of `codemirror.min.mjs`
None of this should be happening, as all the files are exactly the same as the ones on the website.

**Comment by SArpnt** [comment]
> @SArpnt After a long time, I've finally gotten around to installing XAMPP. Running it through there still gives me the same issues when trying to run it from the HTML file: The audio won't start and all of the library entries are empty. I also run into a `globalThis.bytebeat is undefined` error, attributed to character 350715 of `codemirror.min.mjs` None of this should be happening, as all the files are exactly the same as the ones on the website.

xampp has way more stuff than you need (mostly old stuff that most websites don't even use anymore too). it isn't mentioned anywhere in the link i said which provides multiple methods to set up a local web server.

the error happens because of what chasyxx mentioned, the code does a lazy check to see if it's on dollchan. easy to remove if you know what to look for, but still annoying especially considering it's unclear if you even have the website running properly.

[my own bytebeat website](https://bytebeat.ficial.net) has no such check, and the repository has clear documentation on how to work with the code (assuming you already know how to use a cli).

**Comment by eslashblade** [comment]
Over a year later, replying to this. It works offline as long as you have cache. But most of the library will not load and the dropdowns will not open once reloaded offline (and the page will likely crash).
